Repository cancervariants/gene-normalization, pull requests merged in 2023-09, with the labels that each got.

#233 feat!: store source metadata in concepts table
  docs/source/managing_data/dynamodb.rst
  gene/database/dynamodb.py
  gene/etl/hgnc.py
  gene/version.py
  tests/unit/test_database_and_etl.py
Labels: priority:low

#244 feat!: remove search result formatting options
  gene/main.py
  gene/query.py
  gene/schemas.py
  tests/unit/test_ensembl_source.py
  tests/unit/test_hgnc_source.py
  tests/unit/test_ncbi_source.py
  tests/unit/test_query.py
Labels: priority:low

#236 feat!: update data acquisition methods
  docs/source/api/etl_api.rst
  docs/source/managing_data/loading_and_updating_data.rst
  gene/cli.py
  gene/database/postgresql.py
  gene/database/postgresql/create_tables.sql
  gene/etl/__init__.py
  gene/etl/base.py
  gene/etl/ensembl.py
  gene/etl/exceptions.py
  gene/etl/hgnc.py
  gene/etl/ncbi.py
  gene/schemas.py
  tests/unit/data/etl_data/ensembl_GRCh38_110.gff3
  tests/unit/test_database_and_etl.py
  tests/unit/test_ensembl_source.py
  tests/unit/test_hgnc_source.py
  tests/unit/test_ncbi_source.py
Labels: priority:low, vrs-1.x

#242 docs: incorporate Alex feedback
  .pre-commit-config.yaml
  .readthedocs.yaml
  Pipfile
  README.md
  docs/scripts/generate_normalize_figure.py
  docs/source/_static/documents/cgc_2023_poster.pdf
  docs/source/_static/html/normalize_example.html
  docs/source/api/etl_api.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/full_install.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/managing_data/loading_and_updating_data.rst
  docs/source/normalizing_data/normalization.rst
  docs/source/normalizing_data/sources.rst
  docs/source/quick_install.rst
  docs/source/refs.bib
  docs/source/usage.rst
  gene/database/database.py
  gene/database/dynamodb.py
  gene/etl/ensembl.py
  gene/etl/hgnc.py
  gene/query.py
  setup.cfg
Labels: priority:low

#239 build!: use vrs-python for VRS 2.0-alpha models
  .github/workflows/github-actions.yml
  Pipfile
  docs/scripts/generate_normalize_figure.py
  docs/source/_static/html/normalize_otx2p1.html
  docs/source/normalizing_data/normalization.rst
  docs/source/normalizing_data/sources.rst
  gene/database/dynamodb.py
  gene/etl/base.py
  gene/etl/ensembl.py
  gene/etl/hgnc.py
  gene/etl/ncbi.py
  gene/etl/vrs_locations/chromosome_location.py
  gene/etl/vrs_locations/sequence_location.py
  gene/query.py
  gene/schemas.py
  gene/version.py
  setup.cfg
  tests/conftest.py
  tests/unit/test_ensembl_source.py
  tests/unit/test_hgnc_source.py
  tests/unit/test_ncbi_source.py
  tests/unit/test_query.py
  tests/unit/test_schemas.py
Labels: priority:high, build

#245 refactor!: Remove ChromosomeLocation + SequenceLocation classes
  docs/source/api/etl_api.rst
  gene/etl/base.py
  gene/etl/ensembl.py
  gene/etl/hgnc.py
  gene/etl/ncbi.py
  gene/etl/vrs_locations/__init__.py
  gene/etl/vrs_locations/chromosome_location.py
  gene/etl/vrs_locations/sequence_location.py
  tests/unit/test_database_and_etl.py
Labels: priority:low, technical debt

#249 fix: catch ETL module import errors
  gene/cli.py
Labels: priority:low, vrs-1.x

#258 feat!: merge concepts and source dynamodb tables
  docs/source/managing_data/dynamodb.rst
  gene/database/dynamodb.py
  gene/etl/hgnc.py
  gene/version.py
  tests/unit/test_database_and_etl.py
Labels: priority:low

#252 feat!: use vrs 2.0-alpha core gene model in /normalize
  Pipfile
  README.md
  docs/source/index.rst
  docs/source/normalizing_data/normalization.rst
  docs/source/normalizing_data/sources.rst
  docs/source/normalizing_data/vrs_compliance.rst
  docs/source/quick_install.rst
  docs/source/usage.rst
  gene/query.py
  gene/schemas.py
  setup.cfg
  tests/unit/test_ensembl_source.py
  tests/unit/test_ncbi_source.py
  tests/unit/test_query.py
  tests/unit/test_schemas.py
Labels: enhancement, priority:medium
