Repository cancervariants/gene-normalization, pull requests merged in 2023-10, with the labels that each got.

#273 fix: set response_model_exclude_none=True in /normalize
  gene/main.py
Labels: bug, priority:low, vrs-2.0-alpha

#275 cicd: add gh action for closing issue on staging branch
  .github/workflows/close_issue.yml
Labels: priority:low, ci

#277 test: add basic route tests
  Pipfile
  setup.cfg
  tests/unit/test_endpoints.py
Labels: priority:low

#271 build: modernize build configs
  .gitignore
  pyproject.toml
  setup.cfg
  setup.py
  src/gene/__init__.py
  src/gene/cli.py
  src/gene/database/__init__.py
  src/gene/database/database.py
  src/gene/database/dynamodb.py
  src/gene/database/postgresql.py
  src/gene/database/postgresql/add_fkeys.sql
  src/gene/database/postgresql/add_indexes.sql
  src/gene/database/postgresql/create_record_lookup_view.sql
  src/gene/database/postgresql/create_tables.sql
  src/gene/database/postgresql/delete_normalized_concepts.sql
  src/gene/database/postgresql/drop_fkeys.sql
  src/gene/database/postgresql/drop_indexes.sql
  src/gene/etl/__init__.py
  src/gene/etl/base.py
  src/gene/etl/ensembl.py
  src/gene/etl/exceptions.py
  src/gene/etl/hgnc.py
  src/gene/etl/merge.py
  src/gene/etl/ncbi.py
  src/gene/main.py
  src/gene/query.py
  src/gene/schemas.py
  src/gene/version.py
Labels: priority:low

#278 test: add basic route tests
  Pipfile
  setup.cfg
  tests/unit/test_endpoints.py
Labels: priority:low

#281 build: update ga4gh.vrsatile.pydantic version
  Pipfile
  docs/scripts/generate_normalize_figure.py
  pyproject.toml
  src/gene/database/dynamodb.py
  src/gene/etl/vrs_locations/chromosome_location.py
  src/gene/etl/vrs_locations/sequence_location.py
  src/gene/main.py
  src/gene/query.py
  src/gene/schemas.py
  src/gene/version.py
  tests/unit/test_ensembl_source.py
  tests/unit/test_hgnc_source.py
  tests/unit/test_ncbi_source.py
  tests/unit/test_query.py
Labels: priority:medium, build

#283 cicd: update release.yaml (publish python distribution to pypi)
  .github/workflows/release.yml
Labels: priority:medium, ci

#284 cicd: update release.yaml (publish python distribution to pypi)
  .github/workflows/release.yml
Labels: priority:low, ci

#285 refactor: remove unused error handling
  src/gene/main.py
Labels: priority:low

#287 docs: update VRS compliance
  docs/source/normalizing_data/vrs_compliance.rst
Labels: documentation, priority:low

#290 build: properly pin pydantic v2 major version
  Pipfile
  pyproject.toml
Labels: priority:medium, build
