Repository cancervariants/gene-normalization, pull requests merged in 2024-07, with the labels that each got.

#349 fix: correctly configure logging
  src/gene/cli.py
  src/gene/database/dynamodb.py
  src/gene/database/postgresql.py
  src/gene/etl/base.py
  src/gene/etl/ensembl.py
  src/gene/etl/hgnc.py
  src/gene/etl/merge.py
  src/gene/etl/ncbi.py
Labels: priority:low

#351 fix: more logging config fixes
  src/gene/__init__.py
  src/gene/query.py
Labels: priority:medium

#353 build: require >= Python 3.10
  .github/workflows/checks.yaml
  docs/source/install.rst
  pyproject.toml
Labels: priority:high, build

#355 style: update ruff to 0.5.0
  .pre-commit-config.yaml
  Pipfile
  docs/scripts/generate_normalize_figure.py
  docs/source/conf.py
  pyproject.toml
  src/gene/__init__.py
  src/gene/cli.py
  src/gene/database/__init__.py
  src/gene/database/database.py
  src/gene/database/dynamodb.py
  src/gene/database/postgresql.py
  src/gene/etl/__init__.py
  src/gene/etl/base.py
  src/gene/etl/ensembl.py
  src/gene/etl/hgnc.py
  src/gene/etl/merge.py
  src/gene/etl/ncbi.py
  src/gene/main.py
  src/gene/query.py
  src/gene/schemas.py
  src/gene/version.py
  tests/conftest.py
  tests/unit/test_database_and_etl.py
  tests/unit/test_emit_warnings.py
  tests/unit/test_endpoints.py
  tests/unit/test_ensembl_source.py
  tests/unit/test_hgnc_source.py
  tests/unit/test_ncbi_source.py
  tests/unit/test_query.py
  tests/unit/test_schemas.py
Labels: priority:high, cleanup

#358 chore: remove unused configs in pyproject.toml
  pyproject.toml
Labels: priority:medium, chore

#357 style: ruff format
  src/gene/database/database.py
Labels: priority:medium, cleanup

#360 refactor: remove unused code
  src/gene/__init__.py
  src/gene/etl/base.py
  src/gene/etl/hgnc.py
  src/gene/etl/ncbi.py
  src/gene/query.py
  src/gene/schemas.py
  tests/unit/test_hgnc_source.py
  tests/unit/test_ncbi_source.py
  tests/unit/test_query.py
  tests/unit/test_schemas.py
Labels: priority:medium, technical debt

#361 refactor: use DataLicenseAttributes Pydantic model
  src/gene/database/postgresql.py
  src/gene/etl/ensembl.py
  src/gene/etl/hgnc.py
  src/gene/etl/ncbi.py
  src/gene/schemas.py
  tests/unit/test_ensembl_source.py
  tests/unit/test_hgnc_source.py
  tests/unit/test_ncbi_source.py
Labels: priority:medium, technical debt

#356 cicd: update actions + docs workflow from template
  .github/workflows/checks.yaml
Labels: priority:medium, ci

#362 fix(docs): rearrange structure + update ci workflow deps
  .github/workflows/checks.yaml
  docs/source/index.rst
  docs/source/reference/api/database/gene.database.database.rst
  docs/source/reference/api/database/gene.database.dynamodb.rst
  docs/source/reference/api/database/gene.database.postgresql.rst
  docs/source/reference/api/etl/gene.etl.base.rst
  docs/source/reference/api/etl/gene.etl.ensembl.rst
  docs/source/reference/api/etl/gene.etl.exceptions.rst
  docs/source/reference/api/etl/gene.etl.hgnc.rst
  docs/source/reference/api/etl/gene.etl.merge.rst
  docs/source/reference/api/etl/gene.etl.ncbi.rst
  docs/source/reference/api/gene.query.rst
  docs/source/reference/api/gene.schemas.rst
  docs/source/reference/index.rst
Labels: bug, documentation, priority:high

#363 feat: update pre-commit version + add more hooks
  .pre-commit-config.yaml
  Pipfile
  pyproject.toml
Labels: enhancement, priority:low

#365 cicd: target stale workflow rev
  .github/workflows/stale.yaml
Labels: priority:low

#366 refactor: resolve Pylance warnings
  src/gene/schemas.py
Labels: priority:medium, technical debt

#367 build: pin ga4gh.vrs~=2.0.0a10
  Pipfile
  pyproject.toml
Labels: priority:medium, build
